version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/html/
    file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop_pm2_server.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: scripts/install_nodejs_pm2.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 900
      runas: root
  ApplicationStart:
    - location: scripts/start_pm2_server.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: scripts/validate_pm2_service.sh
      timeout: 60
      runas: root